"""AI answer generator for the Phase 7 Authority Engine.

Generates a grounded Quora answer for a question, using the curated industrial
content database (``content_articles``) as the source of truth. When OpenAI is
configured the LLM weaves the matched references into a natural answer; otherwise
a deterministic Markdown template render is used. Both paths return the same
shape: ``{"content_markdown", "quality_score", "used_content_ids"}``.
"""
import json
import re
from typing import Any, Dict, List, Optional

from app.config import settings
from app.models.quora import ContentArticle


def _excerpt(article: ContentArticle, max_len: int = 240) -> str:
    """First clean paragraph of an article's Markdown body."""
    body = (article.body_markdown or "").strip()
    # Drop leading headings / code fences, then take the first paragraph.
    body = re.sub(r"^```.*?```", "", body, flags=re.DOTALL)
    lines = [ln for ln in body.splitlines() if not ln.strip().startswith("#")]
    text = "\n".join(lines).strip()
    if not text:
        text = (article.title or "").strip()
    if len(text) > max_len:
        text = text[:max_len].rsplit(" ", 1)[0].rstrip() + "…"
    return text


def _topic_label(topic: Optional[str]) -> str:
    t = (topic or "").strip()
    return t if t else "this industrial manufacturing topic"


def _render_deterministic(
    question_text: str,
    topic: Optional[str],
    matches: List[ContentArticle],
) -> str:
    """Build a grounded Markdown answer from the matched content articles."""
    label = _topic_label(topic)
    parts: List[str] = []
    parts.append(f"# {question_text.strip()}")
    parts.append("")
    parts.append(
        f"**Short answer:** For {label}, the right approach is driven by the "
        f"part's function, volume, and required tolerance. Below are the "
        f"technical points that matter most, drawn from curated references."
    )
    parts.append("")

    if matches:
        parts.append("## What the technical references say")
        parts.append("")
        for art in matches:
            parts.append(f"- **{art.title.strip()}** — {_excerpt(art)}")
        parts.append("")

        # Synthesize takeaways from matched topics / tags.
        tags: List[str] = []
        for art in matches:
            if art.tags:
                tags.extend([t.strip() for t in art.tags.split(",") if t.strip()])
        seen = set()
        uniq = [t for t in tags if not (t.lower() in seen or seen.add(t.lower()))][:4]

        parts.append("## Key takeaways")
        parts.append("")
        parts.append(
            f"- Match the manufacturing process (die casting, CNC, or tooling) "
            f"to the part's geometry and volume — cost scales with both."
        )
        parts.append(
            f"- Control the variables that actually drive defect rate and "
            f"dimensional stability before optimizing for unit price."
        )
        if uniq:
            parts.append(
                f"- Pay specific attention to: {', '.join(uniq)}."
            )
        parts.append("")

    parts.append("---")
    parts.append(
        "_Generated by the Industrial Authority Engine. Content is grounded in "
        "curated technical references; verify specifics against your own "
        "drawings and specifications before quoting._"
    )
    return "\n".join(parts).strip()


def _score_answer(
    question_text: str,
    matches: List[ContentArticle],
    markdown: str,
) -> int:
    """Deterministic 0-100 quality score for a generated answer."""
    score = 45
    score += min(len(matches) * 12, 36)  # up to +36 for grounded references
    score += min(len(markdown) // 40, 19)  # up to +19 for substantive length
    return max(40, min(100, score))


def _openai_answer(
    question_text: str,
    topic: Optional[str],
    matches: List[ContentArticle],
) -> Dict[str, Any]:
    """Use OpenAI to author a natural, grounded Quora answer."""
    if not settings.openai_api_key:
        raise RuntimeError("OPENAI_API_KEY is not configured.")

    from openai import OpenAI

    client = OpenAI(api_key=settings.openai_api_key)

    references = [
        {"title": a.title, "excerpt": _excerpt(a, max_len=400)}
        for a in matches
    ]
    user_payload = json.dumps(
        {
            "question": question_text,
            "topic": topic or "",
            "references": references,
        },
        ensure_ascii=False,
        indent=2,
    )

    resp = client.chat.completions.create(
        model=settings.openai_model,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a senior manufacturing engineer answering industrial "
                    "Quora questions about die casting, CNC machining, and tooling. "
                    "Answers are technically accurate, concise, and grounded in the "
                    "provided references. Use Markdown. Avoid hype words like "
                    "'revolutionary', 'game-changer', or 'best-in-class'. Cite the "
                    "reference titles where relevant."
                ),
            },
            {
                "role": "user",
                "content": (
                    "Write a helpful Quora answer for the question using the "
                    "references. Return a JSON object with keys: content_markdown "
                    "(the full answer in Markdown) and quality_score (integer 0-100 "
                    "estimating answer usefulness).\n\n"
                    f"Question + references:\n{user_payload}"
                ),
            },
        ],
        response_format={"type": "json_object"},
        temperature=0.4,
    )
    data = json.loads(resp.choices[0].message.content or "{}")
    return {
        "content_markdown": str(data.get("content_markdown") or "").strip(),
        "quality_score": data.get("quality_score"),
    }


def generate_answer(
    question: Any,
    *,
    content_articles: List[ContentArticle],
    use_llm: bool = True,
) -> Dict[str, Any]:
    """Generate a grounded answer for ``question`` from ``content_articles``.

    Args:
        question: a :class:`QuoraQuestion` ORM object or a dict with
            ``question_text`` / ``topic``.
        content_articles: pre-ranked list of matched :class:`ContentArticle`.
        use_llm: when True and OPENAI_API_KEY is set, refine via OpenAI.

    Returns:
        ``{"content_markdown", "quality_score", "used_content_ids"}``.
    """
    if isinstance(question, dict):
        q_text = str(question.get("question_text") or "")
        q_topic = question.get("topic")
    else:
        q_text = str(getattr(question, "question_text", "") or "")
        q_topic = getattr(question, "topic", None)

    matches = list(content_articles or [])
    used_ids = [a.id for a in matches]

    if use_llm and settings.openai_api_key:
        try:
            llm = _openai_answer(q_text, q_topic, matches)
            md = llm.get("content_markdown") or _render_deterministic(
                q_text, q_topic, matches
            )
            score = llm.get("quality_score") or _score_answer(q_text, matches, md)
            return {
                "content_markdown": md,
                "quality_score": max(0, min(100, int(score))),
                "used_content_ids": used_ids,
            }
        except Exception:
            pass  # deterministic fallback

    md = _render_deterministic(q_text, q_topic, matches)
    return {
        "content_markdown": md,
        "quality_score": _score_answer(q_text, matches, md),
        "used_content_ids": used_ids,
    }
