"""Phase 15.4.1: Recommendation Lifecycle foundation

Revision ID: 0035_phase15_recommendation
Revises: 0034_phase15_task_dedup
Create Date: 2026-08-10

Adds the ``recommendations`` table backing the Phase 15.4.1 Recommendation
Lifecycle. A Recommendation is generated by ConversionService.recompute()
(status ``generated``) and later accepted via the Phase 15.3.3 accept endpoint
(status ``accepted``). No SalesTask is created by recompute itself.

Purely additive, single head. Downgrade drops the table.
"""
from alembic import op
import sqlalchemy as sa


revision = "0035_phase15_recommendation"
down_revision = "0034_phase15_task_dedup"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "company_id", sa.Integer(), sa.ForeignKey("company_leads.id"),
            nullable=True,
        ),
        sa.Column(
            "conversion_signal_id", sa.Integer(),
            sa.ForeignKey("conversion_signals.id"), nullable=True,
        ),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), nullable=False,
            server_default="generated",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendations_company_id", "recommendations", ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendations_conversion_signal_id", "recommendations",
        ["conversion_signal_id"], unique=False,
    )
    op.create_index(
        "ix_recommendations_action", "recommendations", ["action"], unique=False,
    )
    op.create_index(
        "ix_recommendations_status", "recommendations", ["status"], unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_recommendations_status", table_name="recommendations")
    op.drop_index("ix_recommendations_action", table_name="recommendations")
    op.drop_index(
        "ix_recommendations_conversion_signal_id", table_name="recommendations"
    )
    op.drop_index("ix_recommendations_company_id", table_name="recommendations")
    op.drop_table("recommendations")
